# For Java 8, try this
# FROM openjdk:8-jdk-alpine

# Refer to Maven build -> finalName
ARG JAR_FILE=request-mapping-service-0.0.1-SNAPSHOT.jar

# cd /opt/app
WORKDIR .

# cp target/request-mapping-service-0.0.1-SNAPSHOT.jar target/original-AWS/app.jar
COPY ${JAR_FILE} app.jar

# java -jar /target/app.jar
ENTRYPOINT ["java","-jar","app.jar"]